version: '3.3'
services:
  model_server:
    image: plumber_server
    networks:
     - traefik-net
    deploy:
      replicas: 10
      labels:
        - "traefik.port=8000"
        - "traefik.backend=echo"
        - "traefik.frontend.rule=Path:/echo"

  traefik:
    image: traefik:latest
    command: --web --docker --docker.swarmmode --docker.watch --logLevel=DEBUG
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    labels:
      - "traefik.enable=false"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  traefik-net:
    driver: overlay

